version: "3.8"

services:
  moodle:
    image: bilinguismotalentum/php74-apache2:1.1.0-redis
    container_name: bilinguismo_moodle
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "aulasquindio.local:host-gateway"
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: host.docker.internal
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: root
      MOODLE_DATABASE_PASSWORD: Tumlab2022*
      MOODLE_DATABASE_NAME: moodle_db
      MOODLE_SKIP_BOOTSTRAP: true
    ports:
      - '5002:80'
      # - '443:8443'
    volumes:
      - '/apps/bilinguismo/moodledata:/var/www/moodledata'
      - '/apps/bilinguismo/moodle:/var/www/html'
  
  front:
    container_name: bilinguismo-frontend
    image: bilinguismotalentum/frontend:2.2.8
    ports: 
      - "3002:3000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "aulasquindio.local:host-gateway"
    environment:
      - KEYCLOAK_CLIENT_ID=si-frontend
      - KEYCLOAK_CLIENT_SECRET=eTIgkF82upQVga3JLCu7XKCyntlo9ieV
      - KEYCLOAK_HOST=http://aulasquindio.local:8080/auth
      - KEYCLOAK_REALM=bilinguismoquindio
      - NEXT_PUBLIC_DEFAULT_AUTH_PROVIDER=keycloak
      - NEXT_PUBLIC_BACKEND=http://aulasquindio.local:4002
      - NEXT_PUBLIC_DATABASE_KEY_NAME=reporter
      - NEXT_PUBLIC_URL_DATA_SYNC=https://sync.aulasquindio.com.co/data
      - NEXTAUTH_URL=http://si.bilinguismoquindio.local

  back:
    container_name: reporter-backend
    image: bilinguismotalentum/backend:1.5.2.2
    ports:
      - "4002:4000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "aulasquindio.local:host-gateway"
    environment:
      DB_DATABASE: "reporter"
      DB_HOST: host.docker.internal
      DB_USER: "root"
      DB_PASSWORD: "%Aqrme3020"
      DB_PORT: "3306"
      JWKS_URI: "https://accounts.bilinguismoquindio.com.co/realms/bilinguismoquindio/protocol/openid-connect/certs"
      KEYCLOAK_DB_HOST: host.docker.internal
      KEYCLOAK_DB_NAME: "keycloak"
      KEYCLOAK_DB_USER: "postgres"
      KEYCLOAK_DB_PASSWORD: "%Aqrme3020"
      KEYCLOAK_DB_PORT: "5432"
      KEYCLOAK_BASE_URL: "http://accounts.aulasquindio.local/auth"
      KEYCLOAK_GET_TOKEN_URL: "/realms/bilinguismoquindio/protocol/openid-connect/token"
      KEYCLOAK_API_URL: "/admin/realms/bilinguismoquindio"
      KEYCLOAK_CLIENT_ID: "client-api"
      KEYCLOAK_CLIENT_SECRET: "zYQeahhrdS50aXjeju6VwF0ZVaFWDmfJ"
      OVERRIDE_DB_HOST : "host.docker.internal"
      OVERRIDE_DB_PASSWORD : "%Aqrme3020"
      OVERRIDE_DB_PORT : 3306
      OVERRIDE_DB_USER : root
